language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: labdevopsdf
  api_key:
    secure: YWKZNohuiNfUu0OvwjB9/MDW3LZKMFZNGhT/wSFxuqOsCRYkFZqJiUkqbQJ5+XjfbLNHNjOkZtkLM4CyHiORgPjzRhqJtLk2bdzQYMZuV+53tk5LiA2/lZnX9jCIPxBYs0kNEZnC4/Bunp1jaAZ5JQ3B+RwO+pUs6F6Sl4aXG+3vD0KdZHbGi0WFISi5kpxTeHHvOmCIw4TdZZeJMC2DsEP2TJ3hCHg/XK8OlCdZ12h1wJeWzASHpZwgElcW8YcAiIO9TFvSAJnM6m+KoWZtv/HEQTasWPUlDY+L1BcaMzh+q9H4EqEuhe8EF/xB3Cnei/JD/708yW0dwTi2AgN2SmYN1IDRRYEdeEplGoi+nrxhwEEHRa4RzXGD9ws9sxZUnIcxAlQbe9t1jorP+pxILXFjcN6z1XlgCf5lnvolyRT+nhnST3eJ8yFUJVK6NYYLCgFCRSdc/kvzInk/8JvokYmnlFuH3AJyAsQD4h1C8mqm15mOnDnRnd0bBrshR9Mk2tnxlWz41pERzCmUBzIPYlIsFbNELyCWv5s0987mQ4nQX5Jdofp0wK43Ut2XMfYyqGpO/a8pheIuHzFgHR0d+10x1SAW6Y57OlkmNCE4QUj5oTTEsaYkRHMWlGmb8bYlLxiA7ba4UVwaDEifB0v9SLcfPOB0g0GTMpnxWe5KX1s=
